# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkbox_download = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_download.setGeometry(QtCore.QRect(20, 180, 121, 31))
        self.checkbox_download.setProperty("allow_download", False)
        self.checkbox_download.setObjectName("checkbox_download")
        self.Python_View = QtWidgets.QGraphicsView(self.centralwidget)
        self.Python_View.setGeometry(QtCore.QRect(10, 10, 600, 150))
        self.Python_View.setObjectName("Python_View")
        self.input_insert_url = QtWidgets.QTextEdit(self.centralwidget)
        self.input_insert_url.setGeometry(QtCore.QRect(160, 180, 441, 31))
        self.input_insert_url.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_insert_url.setProperty("video_url", "")
        self.input_insert_url.setObjectName("input_insert_url")
        self.Image_Python = QtWidgets.QLabel(self.centralwidget)
        self.Image_Python.setGeometry(QtCore.QRect(10, 10, 600, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.Image_Python.sizePolicy().hasHeightForWidth())
        self.Image_Python.setSizePolicy(sizePolicy)
        self.Image_Python.setMaximumSize(QtCore.QSize(600, 150))
        self.Image_Python.setStyleSheet("image: url(:/Logos/Made with Python.png);")
        self.Image_Python.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Image_Python.setText("")
        self.Image_Python.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.Image_Python.setObjectName("Image_Python")
        self.Image_Objetivismo = QtWidgets.QLabel(self.centralwidget)
        self.Image_Objetivismo.setGeometry(QtCore.QRect(10, 479, 600, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.Image_Objetivismo.sizePolicy().hasHeightForWidth())
        self.Image_Objetivismo.setSizePolicy(sizePolicy)
        self.Image_Objetivismo.setMaximumSize(QtCore.QSize(600, 150))
        self.Image_Objetivismo.setStyleSheet("image: url(:/Logos/Objetivismo.png);\n"
"image\n"
"(:/Logos/Objetivismo.png)url(:/Logos/Objetivismo.png)")
        self.Image_Objetivismo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Image_Objetivismo.setText("")
        self.Image_Objetivismo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.Image_Objetivismo.setObjectName("Image_Objetivismo")
        self.input_insert_start_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.input_insert_start_time.setGeometry(QtCore.QRect(160, 270, 118, 22))
        self.input_insert_start_time.setObjectName("input_insert_start_time")
        self.input_insert_end_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.input_insert_end_time.setGeometry(QtCore.QRect(160, 310, 118, 22))
        self.input_insert_end_time.setObjectName("input_insert_end_time")
        self.pushButton_edit_segment = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edit_segment.setGeometry(QtCore.QRect(460, 280, 141, 51))
        self.pushButton_edit_segment.setProperty("start_editing", False)
        self.pushButton_edit_segment.setObjectName("pushButton_edit_segment")
        self.text_end_time = QtWidgets.QLabel(self.centralwidget)
        self.text_end_time.setGeometry(QtCore.QRect(20, 310, 121, 21))
        self.text_end_time.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_end_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_end_time.setObjectName("text_end_time")
        self.text_start_time = QtWidgets.QLabel(self.centralwidget)
        self.text_start_time.setGeometry(QtCore.QRect(20, 270, 121, 21))
        self.text_start_time.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_start_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_start_time.setObjectName("text_start_time")
        self.input_video_filename = QtWidgets.QTextEdit(self.centralwidget)
        self.input_video_filename.setGeometry(QtCore.QRect(160, 220, 441, 31))
        self.input_video_filename.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_video_filename.setProperty("video_filename", "")
        self.input_video_filename.setObjectName("input_video_filename")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 160, 601, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 250, 601, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 450, 581, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 220, 111, 22))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkbox_download_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_download_6.setGeometry(QtCore.QRect(120, 340, 121, 31))
        self.checkbox_download_6.setTristate(True)
        self.checkbox_download_6.setProperty("bool_mp3_format", False)
        self.checkbox_download_6.setObjectName("checkbox_download_6")
        self.input_insert_url_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.input_insert_url_2.setGeometry(QtCore.QRect(20, 410, 301, 31))
        self.input_insert_url_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_insert_url_2.setProperty("video_url", "")
        self.input_insert_url_2.setObjectName("input_insert_url_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 330, 601, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_edit_segment_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edit_segment_2.setGeometry(QtCore.QRect(460, 370, 141, 51))
        self.pushButton_edit_segment_2.setProperty("start_editing", False)
        self.pushButton_edit_segment_2.setObjectName("pushButton_edit_segment_2")
        self.input_insert_url_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.input_insert_url_3.setGeometry(QtCore.QRect(20, 370, 301, 31))
        self.input_insert_url_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_insert_url_3.setProperty("video_url", "")
        self.input_insert_url_3.setObjectName("input_insert_url_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_the_file = QtWidgets.QAction(MainWindow)
        self.actionSelect_the_file.setObjectName("actionSelect_the_file")
        self.menuFile.addAction(self.actionSelect_the_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkbox_download.setText(_translate("MainWindow", "Download Video"))
        self.input_insert_url.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Por favor, insita o link ou o caminho para o vídeo.</p></body></html>"))
        self.input_insert_start_time.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.input_insert_end_time.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.pushButton_edit_segment.setText(_translate("MainWindow", "Download"))
        self.text_end_time.setText(_translate("MainWindow", "Segment end:"))
        self.text_start_time.setText(_translate("MainWindow", "Segment Start:"))
        self.input_video_filename.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Por favor, insira o nome que deseja salvar o arquivo.</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", ".mp4"))
        self.comboBox.setItemText(1, _translate("MainWindow", ".mp3"))
        self.checkbox_download_6.setText(_translate("MainWindow", "Adicionar Capa"))
        self.input_insert_url_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Insira o texto para a capa.</p></body></html>"))
        self.pushButton_edit_segment_2.setText(_translate("MainWindow", "Edit"))
        self.input_insert_url_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Insira o caminho para a capa.</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSelect_the_file.setText(_translate("MainWindow", "Select the file"))
import Pictures_rc

